---

cluster_name: mysql_prod_1
cluster_hosts:
  - { "node_name": "mysql-main-1-1", "public_ip": "172.41.25.45", "private_ip": "ip-172-41-25-45.eu-central-1.compute.internal" }
  - { "node_name": "mysql-main-1-2", "public_ip": "172.41.57.199", "private_ip": "ip-172-41-57-199.eu-central-1.compute.internal" }
  - { "node_name": "mysql-main-1-3", "public_ip": "172.41.91.185", "private_ip": "ip-172-41-91-185.eu-central-1.compute.internal" }

private_ips:
    - ip-172-41-25-45.eu-central-1.compute.internal
    - ip-172-41-57-199.eu-central-1.compute.internal
    - ip-172-41-91-185.eu-central-1.compute.internal

cluster_sst_user:      tree-sst-main-1
cluster_sst_password:  Q16$.Odj3_JeLkwFxE

mysql_wsrep_on: 1

primary_config_group: mysql_prod_1

# paths
script_dir: /usr/local/scripts
mysql_conf_dir: /etc/mysql
mysql_base_dir: /usr/local/mysql
mysql_data_dir: /var/mysql/data
mysql_log_dir: /var/mysql/logs
mysql_tmp_dir: /var/mysql/tmp

permission_group_set:
  - main

superuser_password: ')W4E,U6r2SzrGqCs.f'

pmm_services:
  - linux
  - mysql

mysql_logrotate_min_size: 500M
mysql_logrotate_max_size: 1G
mysql_logrotate_old_files: 7
mysql_logrotate_old_dir: /var/mysql/old-logs

xtrabackup_mysql_user: 'xtrabackup'
xtrabackup_mysql_password: 'iH_xP8DfJ6-G6d3w,j'

mydumper_subdir_set: [ ]

cronjob_dirs:
  - { path: '/var/info',               owner: 'root',  group: 'root',  mode: '755', comment: 'This directory contains system information generated by some scripts' }
  - { path: '/var/backup/structure',   owner: 'root',  group: 'root',  mode: '755', comment: 'This directory contains dumps of database strctures, except for system databases' }
  - { path: '/var/backup/dump',        owner: 'root',  group: 'root',  mode: '755', comment: 'This directory contains complete dumps' }
  - { path: '/var/backup/xtrabackup',  owner: 'root',  group: 'root',  mode: '755', comment: 'This directory contains backups created by Percona Xtrabackup' }

cronjob_set:
  - { name: 'DB complete dump' ,     state: 'enabled',   hour: '1',  minute: '0',   body: '/usr/local/scripts/db-dump.sh' }

