---

- name: Create script_dir
  tags: [ cronjobs ]
  file:
    name: "{{ script_dir }}"
    owner: root
    group: root
    mode: 755
    state: directory

- name: Copy scripts
  tags: [ cronjobs, cronjobs-scripts-update ]
  template:
    src: "./templates/{{ item }}.j2"
    dest: "{{ script_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 755
  with_items:
    - rotate-files.sh
    - db-dump.sh
    - restore-dump.sh

- name: Add scripts path to profile
  tags: [ cronjobs ]
  lineinfile: dest=/etc/profile line="export PATH=$PATH:{{ script_dir }}"

- name: Create directories needed by the cronjobs
  tags: [ cronjobs, cronjobs-scripts-update ]
  file:
    name: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items: "{{ cronjob_dirs }}"

- name: Create directory manifests
  tags: [ cronjobs, cronjobs-scripts-update ]
  shell:
    cmd: "echo '{{ item.comment }}' > {{ item.path }}/_MANIFEST"
  with_items: "{{ cronjob_dirs }}"

- name: Add jobs, if any
  tags: [ cronjobs, cronjobs-jobs-update ]
  cron:
    name: "{{ item.name }}"
    hour: "{{ item.hour }}"
    minute: "{{ item.minute }}"
    job: "{{ item.body }}"
    state: "{{ {'enabled': 'present', 'disabled': 'absent'}[item.state] | default('present') }}"
  with_items: "{{ cronjob_set }}"

